# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180107_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/products_images/'),
        ),
    ]
